LINE = g++ -std=c++20 -Wall -Wextra -Wpedantic -Wfatal-errors

dijkstras: dijkstras.cpp dijkstras_main.cpp dijkstras.h
	$(LINE) dijkstras.cpp dijkstras_main.cpp -o dijkstras

clean:
	/bin/rm -f dijkstras
